/**
 * voicePdfGenerator.js
 * Generates an official Adepec Homes Digital Expense Voucher PDF for missing receipts.
 */

export async function generateVoiceExpenseVoucherPdf({
  amount = 60.00,
  vendor = 'Gas Station',
  category = 'Project Overhead & Bills',
  phase = 'Extra Costs & Misc',
  project = 'Lot 103',
  date = new Date().toISOString().split('T')[0],
  note = 'Voice expense voucher for missing receipt'
}) {
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const voucherId = `VCH-${Date.now().toString().slice(-6)}`;
  const cleanAmount = typeof amount === 'number' ? amount : parseFloat(amount) || 0;
  const formattedAmount = `$${cleanAmount.toFixed(2)}`;

  // Colors
  const ADEPEC_GOLD = [197, 160, 89]; // #C5A059
  const DARK_BG = [24, 24, 27];        // Zinc 900
  const LIGHT_GRAY = [244, 244, 245];  // Zinc 100
  const TEXT_DARK = [39, 39, 42];      // Zinc 800

  // 1. Top Header Banner
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, 210, 40, 'F');

  // Gold accent bar
  doc.setFillColor(...ADEPEC_GOLD);
  doc.rect(0, 40, 210, 3, 'F');

  // Header Title & Subtitle
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('ADEPEC HOMES', 15, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...ADEPEC_GOLD);
  doc.text('DIGITAL EXPENSE VOUCHER & RECEIPT', 15, 26);

  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text(`Voucher ID: ${voucherId} | Date: ${date}`, 15, 34);

  // 2. Voucher Detail Card Container
  doc.setFillColor(...LIGHT_GRAY);
  doc.roundedRect(15, 52, 180, 110, 3, 3, 'F');
  doc.setDrawColor(...ADEPEC_GOLD);
  doc.setLineWidth(0.5);
  doc.roundedRect(15, 52, 180, 110, 3, 3, 'S');

  // Amount Highlight Box inside card
  doc.setFillColor(...DARK_BG);
  doc.roundedRect(125, 60, 60, 25, 2, 2, 'F');
  doc.setTextColor(...ADEPEC_GOLD);
  doc.setFontSize(9);
  doc.text('TOTAL AMOUNT', 130, 68);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(formattedAmount, 130, 78);

  // Details List
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_DARK);

  let startY = 68;
  const lineGap = 11;

  const fields = [
    { label: 'Project / Lot:', value: project },
    { label: 'Vendor / Payee:', value: vendor },
    { label: 'Trade Category:', value: category.replace(/_/g, ' ') },
    { label: 'Trade Phase:', value: phase },
    { label: 'Transaction Date:', value: date },
    { label: 'Source Method:', value: 'Hands-Free Truck Voice Assistant' }
  ];

  fields.forEach(f => {
    doc.setFont('helvetica', 'bold');
    doc.text(f.label, 25, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(String(f.value), 65, startY);
    startY += lineGap;
  });

  // Note Box at bottom of card
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(25, 130, 160, 22, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ADEPEC_GOLD);
  doc.text('NOTE / DESCRIPTION:', 30, 137);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...TEXT_DARK);
  doc.text(note, 30, 145);

  // 3. Authorization Stamp / Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('This is an official digital voucher generated by Adepec Homes Mobile Scanner App.', 15, 175);
  doc.text('Uploaded directly to Google Drive for automated spreadsheet data entry.', 15, 180);

  // Convert to Blob & File
  const pdfBlob = doc.output('blob');
  const sanitizedProject = project.replace(/[^a-z0-9]/gi, '_');
  const filename = `Voucher_${sanitizedProject}_${cleanAmount.toFixed(0)}_${date}.pdf`;
  const pdfFile = new File([pdfBlob], filename, { type: 'application/pdf' });

  return {
    blob: pdfBlob,
    file: pdfFile,
    filename,
    voucherId,
    formattedAmount
  };
}
